vim9script noclear

# LOAD SCRIPTS {{{1
###############################################################################
# Functions are namespaced in a corresponding autoload/<namespace>.vim script
import expand("$HOME/.vim/init/plug.vim")
import expand("$HOME/.vim/init/general.vim")
import expand("$HOME/.vim/init/commands.vim")
import expand("$HOME/.vim/init/keymappings.vim")
import expand("$HOME/.vim/init/plugins.vim")
import expand("$HOME/.vim/init/autocommands.vim")
# }}}
