  require('raoulmillais.plug')
  require('raoulmillais.general')
  require('raoulmillais.commands')
  require('raoulmillais.autocommands')
  require('raoulmillais.keymappings')
  require('raoulmillais.plugins')
